---
- hosts: servers
  vars_files:
    - settings.yml
  roles:
    - ubuntu-server
    - memcached
    - php5
    - openjdk7
    #- oracle_java7
    - nginx
    - mysql
    - apache
    - phpmyadmin
    - beanstalkdaemon
    - beanstalkclient
    - selenium
    #- supervisord
    #- elasticsearch
