---

- name: Install MySQL
  action: apt name="{{ item }}"  state=latest update_cache=true
  sudo: yes
  with_items:
    - python-mysqldb
    - mysql-server
- name: Start the MySQL service
  action: service name=mysql state=started
  sudo: yes
- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ parameters.mysql.root_password }} priv=*.*:ALL,GRANT
  sudo: yes
  with_items:
    - "{{ parameters.mysql.ip }}"
    - 127.0.0.1
    - ::1
    - "%"
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=root.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  sudo: yes
  notify:
    - RestartMysql

- name: set mysql my.cnf
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root mode=0644
  sudo: yes
  notify:
    - RestartMysql

- name: delete anonymous MySQL server user for $server_hostname
  action: mysql_user user="" host="$server_hostname" state="absent"
  sudo: yes

- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"
  sudo: yes

- name: remove the MySQL test database
  action: mysql_db db=test state=absent
  sudo: yes

- name: Add MySQL databases
  action: mysql_db db={{ item.name }} state=present
  sudo: yes
  with_items: parameters.databases

- name: Add MySQL users (allowing to connect from everywhere)
  mysql_user: name={{ item.username }} host="%" password={{ item.password }} priv={{ item.db_name }}.*:ALL,GRANT
  sudo: yes
  with_items: parameters.database_users
