---
- lineinfile: "dest=/etc/apache2/ports.conf regexp='^Listen 80' line='Listen {{ parameters.apache.port }}' backrefs=yes"
  notify:
    - RestartApache
  sudo: yes
- lineinfile: "dest=/etc/apache2/sites-available/000-default.conf regexp='^<VirtualHost \\*:80>' line='<VirtualHost *:{{ parameters.apache.port }}>' backrefs=yes"
  notify:
    - RestartApache
  sudo: yes
