---
- name: Installs apache web server
  apt: pkg={{ item }} state=latest update_cache=true
  sudo: yes
  with_items:
    - apache2
    - libapache2-mod-php5

- lineinfile: "dest=/etc/apache2/ports.conf regexp='^Listen 80' line='Listen {{ apache.port }}' backrefs=yes"
  sudo: yes
  notify:
    - RestartApache
- lineinfile: "dest=/etc/apache2/sites-available/000-default.conf regexp='^<VirtualHost \\*:80>' line='<VirtualHost *:{{ apache.port }}>' backrefs=yes"
  sudo: yes
  notify:
    - RestartApache
