---
- name: Install selenium related packages
  action: apt name="{{ item }}" state=latest update_cache=true
  sudo: yes
  with_items:
    - openjdk-6-jre-headless 
    - xfonts-100dpi 
    - xfonts-75dpi 
    - xfonts-scalable 
    - xfonts-cyrillic
    - xserver-xorg-core
    - xvfb
    - firefox
- name: Add screen to crontab on restart
  cron: name="setup selenium screen on restart" special_time=reboot job="sh -c 'Xvfb :99 -ac -screen 0 1024x768x8 > /tmp/xvfb.log 2>&1 &'"
  sudo: yes
- name: Create selenium folder
  action: file path={{ parameters.selenium.path }} state=directory mode=0777
  sudo: yes    
- name: Create selenium log folder
  action: file path={{ parameters.selenium.log_path }} state=directory mode=0777
  sudo: yes   
- name: Download selenium
  shell: wget {{ parameters.selenium.url}}
  sudo: yes     
  args:
    chdir: "{{ parameters.selenium.path }}"
    creates: "{{parameters.selenium.path}}/{{parameters.selenium.filename}}"
- name: Install service
  template: src=selenium.j2 dest=/etc/init.d/selenium owner=root group=root mode=755
  sudo: yes

- name: Add selenium service as startup script
  shell: update-rc.d selenium defaults
  sudo: yes     


