---
- name: Install elasticsearch repo key
  shell: "wget -O - http://packages.elasticsearch.org/GPG-KEY-elasticsearch | apt-key add -"
  sudo: yes
- name: Add repo
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.2/debian stable main' state=present
  sudo: yes
- name: Install elasticsearch packages
  action: apt name="{{ item }}" state=latest update_cache=true
  sudo: yes
  with_items:
    - elasticsearch
- name: Start the elasticsearch service
  action: service name=elasticsearch state=started
  sudo: yes
